Corrected the automation of the EC2 IP fetching.

diff --git a/.github/workflows/project_auto_testing.yaml b/.github/workflows/project_auto_testing.yaml
--- a/.github/workflows/project_auto_testing.yaml
+++ b/.github/workflows/project_auto_testing.yaml
@@ -15,9 +15,19 @@ jobs:
     steps:
       - name: Fetch EC2 Public IP
         id: set_ip
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: 'us-east-1'
         run: |
           IP=$(aws ec2 describe-instances --instance-ids i-0598dd777bcbfdf21 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
-          echo "::set-output name=ec2_ip::$IP"
+          if [ $? -eq 0 ]; then
+            echo "::set-output name=ec2_ip::$IP"
+          else
+            echo "AWS CLI command failed:"
+            echo $IP
+            exit 1
+          fi
   on-success:
     runs-on: ubuntu-latest
     needs:
@@ -33,7 +43,6 @@ jobs:
           username: ubuntu
           key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
           script: |
-
             curl -O -L https://raw.githubusercontent.com/alonitac/PolybotServiceDocker/main/test/test-compose-project.sh
             bash test-compose-project.sh
 
diff --git a/.github/workflows/service-deploy.yaml b/.github/workflows/service-deploy.yaml
--- a/.github/workflows/service-deploy.yaml
+++ b/.github/workflows/service-deploy.yaml
@@ -13,9 +13,19 @@ jobs:
     steps:
       - name: Fetch EC2 Public IP
         id: set_ip
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: 'us-east-1'
         run: |
           IP=$(aws ec2 describe-instances --instance-ids i-0598dd777bcbfdf21 --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
-          echo "::set-output name=ec2_ip::$IP"
+          if [ $? -eq 0 ]; then
+            echo "::set-output name=ec2_ip::$IP"
+          else
+            echo "AWS CLI command failed:"
+            echo $IP
+            exit 1
+          fi
 
   MongoInitBuild:
     runs-on: ubuntu-latest
@@ -24,13 +34,15 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Build and push image
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: 'us-east-1'
         run: |
           cd mongo
 
           # Login to ECR (commend in in case you use ECR, change region code and ECR URI):
-          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
-          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 019273956931.dkr.ecr.us-east-1.amazonaws.com
+          aws ecr get-login-password --region ${{ env.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin 019273956931.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com
 
           # Define the base name of the image and the tag separately
           IMAGE_BASE_NAME=mongo-init
